# Project  ML2 : PREDICTING BEJINGS AIR POLLUTION 
---------------------------------------------------------------------

Instructions for the format in which the submission file should be uploaded:

The submission file should be in the csv format.

If the submission csv file is not in the same format as the sample submission file, it won’t be considered for evaluation.

It should have 16728 rows.

It should only have 2 columns, 1st column: REF_NO values, and 2nd column: predicted PM2.5 values.

The submission file should not have column names in the first row.

It’s suggested to set index=False, and header=False while using pd.to_csv to save the predictions to a csv file.

Example

sub_df.to_csv(‘submission.csv’, index=False, header=False)

Do not change the order of rows in the submission file. It should be the same as the sample submission file.

#### Evaluation Metric

Evaluation Metric

The model evaluation will be based on the RMSE Score score.

To learn more about RMSE and it’s Python implementation, 

#### Installation

In [1]:
# !pip install pandas      # Importing package pandas (For data manipulation and analysis in Python)
# !pip install numpy       # Importing package numpys (For Numerical Python)
# !pip install -q datascience  # Package that is required by pandas profiling
# !pip install -q pandas-profiling 

#### Initialization of libreary

In [150]:
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport 
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.ensemble import RandomForestClassifier  # Choose an appropriate model
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

#### Data Acquisition

In [151]:
train_data = pd.read_csv('beijing_train.csv')
test_data = pd.read_csv('beijing_test.csv')

In [152]:
train_data.head()

REF_NO  year  month  day  hour  PM2.5  PM10   SO2   NO2     CO    O3  TEMP  \
0       1  2013      3    1     0    4.0   4.0   4.0   7.0  300.0  77.0  -0.7   
1       2  2013      3    1     1    8.0   8.0   4.0   7.0  300.0  77.0  -1.1   
2       3  2013      3    1     2    7.0   7.0   5.0  10.0  300.0  73.0  -1.1   
3       4  2013      3    1     3    6.0   6.0  11.0  11.0  300.0  72.0  -1.4   
4       5  2013      3    1     4    3.0   3.0  12.0  12.0  300.0  72.0  -2.0   

     PRES  DEWP  RAIN   wd  WSPM       station  
0  1023.0 -18.8   0.0  NNW   4.4  Aotizhongxin  
1  1023.2 -18.2   0.0    N   4.7  Aotizhongxin  
2  1023.5 -18.2   0.0  NNW   5.6  Aotizhongxin  
3  1024.5 -19.4   0.0   NW   3.1  Aotizhongxin  
4  1025.2 -19.5   0.0    N   2.0  Aotizhongxin

In [153]:
test_data.head()

REF_NO  year  month  day  hour   PM10   SO2    NO2      CO    O3  TEMP  \
0   33649  2017      1    1     0  496.0   8.0  121.0  6100.0   4.0  -4.7   
1   33650  2017      1    1     1  497.0   7.0  113.0  6300.0   4.0  -5.2   
2   33651  2017      1    1     2  469.0   7.0  111.0  6200.0   4.0  -5.4   
3   33652  2017      1    1     3  425.0   6.0  109.0  5900.0   3.0  -5.2   
4   33653  2017      1    1     4  468.0  10.0  123.0  7700.0  16.0  -5.0   

     PRES  DEWP  RAIN   wd  WSPM       station  
0  1022.1  -6.1   0.0  ENE   1.0  Aotizhongxin  
1  1022.3  -6.4   0.0    E   0.7  Aotizhongxin  
2  1022.5  -6.5   0.0  ENE   1.1  Aotizhongxin  
3  1022.5  -6.2   0.0    E   1.1  Aotizhongxin  
4  1021.9  -5.8   0.0  ENE   1.0  Aotizhongxin

#### Data Description

In [154]:
train_data.describe()

REF_NO           year          month            day  \
count  403776.000000  403776.000000  403776.000000  403776.000000   
mean    16824.500000    2014.564194       6.735378      15.748217   
std      9713.352953       1.097503       3.356479       8.808891   
min         1.000000    2013.000000       1.000000       1.000000   
25%      8412.750000    2014.000000       4.000000       8.000000   
50%     16824.500000    2015.000000       7.000000      16.000000   
75%     25236.250000    2016.000000      10.000000      23.000000   
max     33648.000000    2016.000000      12.000000      31.000000   

                hour          PM2.5           PM10            SO2  \
count  403776.000000  395301.000000  397554.000000  395000.000000   
mean       11.500000      79.248275     104.327897      15.733060   
std         6.922195      79.146708      90.136400      21.739455   
min         0.000000       2.000000       2.000000       0.285600   
25%         5.750000      21.000000      36.000000       2.000000   
50%        11.500000      55.000000      83.000000       7.000000   
75%        17.250000     110.000000     145.000000      19.000000   
max        23.000000     999.000000     999.000000     500.000000   

                 NO2             CO             O3           TEMP  \
count  391917.000000  383515.000000  390769.000000  403512.000000   
mean       50.352785    1214.843339      58.119327      14.088899   
std        34.771910    1124.285676      57.375966      11.303534   
min         1.026500     100.000000       0.214200     -19.900000   
25%        23.000000     500.000000      11.000000       4.000000   
50%        43.000000     900.000000      45.000000      15.400000   
75%        71.000000    1500.000000      83.000000      23.500000   
max       290.000000   10000.000000    1071.000000      41.600000   

                PRES           DEWP           RAIN           WSPM  
count  403511.000000  403507.000000  403515.000000  403538.000000  
mean     1010.282534       3.157291       0.067052       1.718380  
std        10.356778      13.617273       0.837845       1.237965  
min       982.400000     -43.400000       0.000000       0.000000  
25%      1002.000000      -8.000000       0.000000       0.900000  
50%      1009.800000       4.200000       0.000000       1.400000  
75%      1018.300000      15.500000       0.000000       2.200000  
max      1042.800000      29.100000      72.500000      13.200000

#### Data Information

In [155]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403776 entries, 0 to 403775
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   REF_NO   403776 non-null  int64  
 1   year     403776 non-null  int64  
 2   month    403776 non-null  int64  
 3   day      403776 non-null  int64  
 4   hour     403776 non-null  int64  
 5   PM2.5    395301 non-null  float64
 6   PM10     397554 non-null  float64
 7   SO2      395000 non-null  float64
 8   NO2      391917 non-null  float64
 9   CO       383515 non-null  float64
 10  O3       390769 non-null  float64
 11  TEMP     403512 non-null  float64
 12  PRES     403511 non-null  float64
 13  DEWP     403507 non-null  float64
 14  RAIN     403515 non-null  float64
 15  wd       402387 non-null  object 
 16  WSPM     403538 non-null  float64
 17  station  403776 non-null  object 
dtypes: float64(11), int64(5), object(2)
memory usage: 55.5+ MB


In [156]:
train_data.groupby(['station']).sum().sort_values(['PM2.5'],ascending=True)[['O3','PM2.5']]

O3      PM2.5
station                               
Dingling       2.244930e+06  2166259.9
Huairou        1.963692e+06  2271054.0
Changping      1.950302e+06  2325708.2
Shunyi         1.794428e+06  2580792.7
Tiantan        1.866372e+06  2687998.8
Aotizhongxin   1.813035e+06  2693141.3
Guanyuan       1.827848e+06  2730033.8
Gucheng        1.940789e+06  2744562.2
Wanliu         1.560752e+06  2759924.9
Wanshouxigong  1.864146e+06  2773167.5
Nongzhanguan   1.971963e+06  2780055.0
Dongsi         1.912975e+06  2814224.1

In [157]:
df = train_data

In [158]:
parameter_of_interest = "O3"
parameter_of_interest_2 = "PM2.5"
# Find the station with the overall lowest pollution level for the chosen parameter
min_pollution_station = df.loc[df[parameter_of_interest].idxmin()][parameter_of_interest_2]
min_pollution_station

38.0

In [159]:
for trn in train_data.columns:
    print("\n===========\n")
    print(trn)
    print("===========\n")
    print(train_data[trn].unique())



REF_NO

[    1     2     3 ... 33646 33647 33648]


year

[2013 2014 2015 2016]


month

[ 3  4  5  6  7  8  9 10 11 12  1  2]


day

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]


hour

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


PM2.5

[  4.    8.    7.    6.    3.    5.    9.   10.   11.   12.   15.   24.
  22.   14.   13.   18.   26.   25.   37.   44.   54.   61.   67.   74.
  81.   93.  112.  109.  110.  105.  106.  101.   91.   79.   77.   83.
  94.   96.   98.   72.   48.   28.   19.   60.  117.   46.   42.   49.
  34.   16.   20.   31.   40.   51.   58.   71.  100.  103.  115.  104.
 111.  114.  131.  138.  142.  163.  168.  165.  166.  190.  203.  210.
 205.  215.  219.  226.  284.  272.  242.  212.  192.  188.  186.  194.
 184.  175.  179.  201.  230.  246.  248.  239.  254.  266.  260.  250.
 240.  238.  243.  275.  306.  320.  292.  251.  228.  217.  255.  258.
 277.  282.  267.  216.  211.

In [160]:
train_data.columns

Index(['REF_NO', 'year', 'month', 'day', 'hour', 'PM2.5', 'PM10', 'SO2', 'NO2',
       'CO', 'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'wd', 'WSPM', 'station'],
      dtype='object')

In [161]:
label_encoder = LabelEncoder()
categorical_columns = ['station','wd']
for column in categorical_columns:
    train_data[column] = label_encoder.fit_transform(train_data[column])
print(train_data)

        REF_NO  year  month  day  hour  PM2.5   PM10   SO2    NO2      CO  \
0            1  2013      3    1     0    4.0    4.0   4.0    7.0   300.0   
1            2  2013      3    1     1    8.0    8.0   4.0    7.0   300.0   
2            3  2013      3    1     2    7.0    7.0   5.0   10.0   300.0   
3            4  2013      3    1     3    6.0    6.0  11.0   11.0   300.0   
4            5  2013      3    1     4    3.0    3.0  12.0   12.0   300.0   
...        ...   ...    ...  ...   ...    ...    ...   ...    ...     ...   
403771   33644  2016     12   31    19  449.0  487.0  10.0  153.0  4500.0   
403772   33645  2016     12   31    20  460.0  492.0  12.0  146.0  4100.0   
403773   33646  2016     12   31    21  463.0  498.0  12.0  141.0  4400.0   
403774   33647  2016     12   31    22  493.0  537.0  12.0  124.0  5000.0   
403775   33648  2016     12   31    23  464.0  490.0   8.0  111.0  5400.0   

          O3  TEMP    PRES  DEWP  RAIN  wd  WSPM  station  
0       77.0  -

In [162]:
non_numeric_columns = ['REF_NO', 'year', 'month', 'day', 'hour', 'PM2.5', 'PM10', 'SO2', 'NO2',
       'CO', 'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'WSPM']
for column in non_numeric_columns:
    train_data[column] = pd.to_numeric(train_data[column], errors='coerce')
print(train_data)

        REF_NO  year  month  day  hour  PM2.5   PM10   SO2    NO2      CO  \
0            1  2013      3    1     0    4.0    4.0   4.0    7.0   300.0   
1            2  2013      3    1     1    8.0    8.0   4.0    7.0   300.0   
2            3  2013      3    1     2    7.0    7.0   5.0   10.0   300.0   
3            4  2013      3    1     3    6.0    6.0  11.0   11.0   300.0   
4            5  2013      3    1     4    3.0    3.0  12.0   12.0   300.0   
...        ...   ...    ...  ...   ...    ...    ...   ...    ...     ...   
403771   33644  2016     12   31    19  449.0  487.0  10.0  153.0  4500.0   
403772   33645  2016     12   31    20  460.0  492.0  12.0  146.0  4100.0   
403773   33646  2016     12   31    21  463.0  498.0  12.0  141.0  4400.0   
403774   33647  2016     12   31    22  493.0  537.0  12.0  124.0  5000.0   
403775   33648  2016     12   31    23  464.0  490.0   8.0  111.0  5400.0   

          O3  TEMP    PRES  DEWP  RAIN  wd  WSPM  station  
0       77.0  -

In [163]:
train_data = train_data.dropna()

In [164]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 367283 entries, 0 to 403775
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype  
---  ------   --------------   -----  
 0   REF_NO   367283 non-null  int64  
 1   year     367283 non-null  int64  
 2   month    367283 non-null  int64  
 3   day      367283 non-null  int64  
 4   hour     367283 non-null  int64  
 5   PM2.5    367283 non-null  float64
 6   PM10     367283 non-null  float64
 7   SO2      367283 non-null  float64
 8   NO2      367283 non-null  float64
 9   CO       367283 non-null  float64
 10  O3       367283 non-null  float64
 11  TEMP     367283 non-null  float64
 12  PRES     367283 non-null  float64
 13  DEWP     367283 non-null  float64
 14  RAIN     367283 non-null  float64
 15  wd       367283 non-null  int64  
 16  WSPM     367283 non-null  float64
 17  station  367283 non-null  int64  
dtypes: float64(11), int64(7)
memory usage: 53.2 MB


In [165]:
X = train_data.drop(['REF_NO', 'PM2.5'], axis=1)
y = train_data['PM2.5']

In [166]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [167]:
y_train

337000     77.0
179002    127.0
242606      9.0
38129      67.0
130051     24.0
          ...  
285134      8.0
402312     19.0
147508    131.0
162867     72.0
135700     52.0
Name: PM2.5, Length: 293826, dtype: float64

In [138]:
model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [139]:
y_pred = model.predict(X_test)

In [140]:
mse = mean_squared_error(y_test, y_pred)

# Calculate Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)

print(f"RMSE: {rmse}")

RMSE: 16.927864442075943


### Same things begin with Test data

In [169]:
label_encoder = LabelEncoder()
categorical_columns = ['station','wd']
for column in categorical_columns:
    test_data[column] = label_encoder.fit_transform(test_data[column])
non_numeric_columns = ['REF_NO', 'year', 'month', 'day', 'hour', 'PM10', 'SO2', 'NO2',
       'CO', 'O3', 'TEMP', 'PRES', 'DEWP', 'RAIN', 'WSPM']
for column in non_numeric_columns:
    test_data[column] = pd.to_numeric(test_data[column], errors='coerce')
print(submission_data)

       REF_NO  year  month  day  hour   PM10   SO2    NO2      CO    O3  TEMP  \
0       33649  2017      1    1     0  496.0   8.0  121.0  6100.0   4.0  -4.7   
1       33650  2017      1    1     1  497.0   7.0  113.0  6300.0   4.0  -5.2   
2       33651  2017      1    1     2  469.0   7.0  111.0  6200.0   4.0  -5.4   
3       33652  2017      1    1     3  425.0   6.0  109.0  5900.0   3.0  -5.2   
4       33653  2017      1    1     4  468.0  10.0  123.0  7700.0  16.0  -5.0   
...       ...   ...    ...  ...   ...    ...   ...    ...     ...   ...   ...   
16723   35060  2017      2   28    19   32.0   3.0   24.0   400.0  72.0  12.5   
16724   35061  2017      2   28    20   32.0   3.0   41.0   500.0  50.0  11.6   
16725   35062  2017      2   28    21   28.0   4.0   38.0   500.0  54.0  10.8   
16726   35063  2017      2   28    22   23.0   4.0   30.0   400.0  59.0  10.5   
16727   35064  2017      2   28    23   19.0   4.0   38.0   600.0  49.0   8.6   

         PRES  DEWP  RAIN  

In [170]:
submission_data = submission_data.dropna()

In [171]:
submission_features = submission_data.drop(['REF_NO'], axis=1)
submission_predictions = model.predict(submission_features)

In [172]:
submission_df = pd.DataFrame({'REF_NO': submission_data['REF_NO'], 'PM2.5': submission_predictions})

In [173]:
submission_df.to_csv('submission_predictions.csv', index=False, header=False)

#### the output file has submission_predictions.csv to submit.